name: Deploy to AWS EBS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # Run our unit tests using the test application
      - name: Run unit tests
        run: pytest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t amoshochman/hello-world:latest .
          docker push amoshochman/hello-world:latest
        env:
            DOCKER_BUILDKIT: 1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to AWS Elastic Beanstalk
        run: |
          # Install AWS CLI
          pip install awscli --upgrade --user
          export PATH=$PATH:~/.local/bin

          # Create a temporary directory
          mkdir temp

          # Save the Docker image as a TAR file
          docker save amoshochman/hello-world:latest | gzip > temp/image.tar.gz

          # Create a ZIP file containing the TAR file
          cd temp
          zip -r ../docker-image.zip .

          # Upload the ZIP file to S3 bucket
          aws s3 cp ../docker-image.zip s3://amos-simple-bucket/docker-image.zip

          # Clean up temporary files
          cd ..
          rm -rf temp

          # Create a new application version in Elastic Beanstalk
          aws elasticbeanstalk create-application-version \
            --application-name hello-world \
            --version-label v1.0.0 \
            --source-bundle S3Bucket=amos-simple-bucket,S3Key=docker-image.zip

          # Update the environment to use the new application version
          aws elasticbeanstalk update-environment \
            --environment-name Hello-world-env \
            --version-label v1.0.0
      
